language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r spring-webservice *
  - mkdir -p deploy
  - mv spring-webservice.zip deploy/spring-webservice.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
  bucket: spring-webservice-deploy-mwe # 6-3-3에서 생성한 S3 버킷
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  local_dir: deploy
  wait-until-deployed: true
  on:
    repo: MoonjWll/spring-webservice #Github 주소
    branch: main

 provider: codedeploy
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
 bucket: spring-webservice-deploy-mwe
 key: spring-webservice.zip
 bundle_type: zip
 deployment_group: spring-webservice-group
 region: ap-northeast-2
 wait-until-deployed: true
 on:
  repo: MoonjWll/spring-webservice
  branch: main

notifications:
  email:
    recipients:
      - mjw0147@gmail.com
