language: java
jdk:
  - openjdk11

branches:
  only:
    - main

#----- Travis CI에서 Push 후 반응이 없는 경우 프로젝트의 GIthub Repository가 바로 루트 경로에 있지 않은 확률이 높음.addons:
#--- 해당 레포지토리에서 추가로 폴더를 생성하여 프로젝트가 생성된 경우!
#--- 이럴 때, travis.yml을 build.gradle이 위치한 곳이 아니라 레포지토리 루트 경로에 생성해야한다.
#--- 그 이후 아래 코드로 현재 위치로부터 프로젝트 빌드 진행할 곳으로 이동 필요하기 때문
#before_script:
#  -cd spring-webservice/
#-----

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - mjw0147@gmail.com