spring:
  profiles:
    active: local
    group:
      set1: set1, real-db
      set2: set2, real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb



# local 환경.
---
spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: classpath:data-h2.sql;MODE=MYSQL
  h2:
    console:
      enabled: true

spring.config:
  location: classpath:application-set1.yml


